import { Product, ProductStatus } from "../../domain/product.entity";
// TODO [EXTRACCION]: import a modulo no incluido en este repo -> Dexie/IndexedDB offline (EXCLUIDO). Resolver: copiar/stubear o eliminar.
import { LocalProduct } from "@/lib/db";

export class LocalProductMapper {
    static toLocal(product: Product, syncStatus: 'pending' | 'synced' | 'failed' = 'synced'): LocalProduct {
        const primitives = product.toPrimitives();
        return {
            id: primitives.id, // UUID
            tenant_id: primitives.tenant_id,
            name: primitives.name,
            price: primitives.price, // number
            cost: primitives.cost,   // number
            stock: primitives.stock,
            sku: primitives.sku,
            category_id: primitives.category_id, // UUID string
            description: primitives.description,
            image_path: primitives.image_path ?? undefined,
            sync_status: syncStatus,
            last_updated_at: Date.now(),
            is_deleted: false,
            // Note: local_id is auto-generated by Dexie, so we don't set it here unless updating an existing local record.
        };
    }

    static toDomain(local: LocalProduct): Product {
        return Product.createProduct(
            local.id || '', // Should always be present for synced products
            local.name,
            local.price,
            local.cost,
            local.description || '',
            local.stock,
            local.category_id || '',
            local.sku,
            local.tenant_id,
            undefined, // expirationDate - not currently in LocalProduct, maybe add if needed?
            local.stock === 0 ? ProductStatus.OUT_OF_STOCK : ProductStatus.ACTIVE, // Simplistic status mapping for offline
            [], // seasonIds - Dexie doesn't store relations deeply yet
            local.image_path
        );
    }
}
